server:
  port: 28080

spring:
  application:
    name: demo

  datasource:
    url: jdbc:mysql://localhost:3306/demo
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.iwhalecloud.oss.res.aop
  configuration:
    map-underscore-to-camel-case: true
    jdbc-type-for-null: 'NULL'